# Generated by Django 4.2.27 on 2026-02-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentintent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MOCK', 'Mock')], default='MOCK', max_length=32)),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('signature_ok', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='purpose',
            field=models.CharField(blank=True, choices=[('TOPUP', 'Topup'), ('CHECKOUT', 'Checkout')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='amount',
            field=models.PositiveIntegerField(help_text='Kuruş'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='INITIATED', max_length=16),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['user', 'created_at'], name='payments_pa_user_id_d325fd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['purpose', 'status', 'created_at'], name='payments_pa_purpose_2d6274_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['provider_payment_id'], name='payments_pa_provide_89c1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='providerevent',
            index=models.Index(fields=['provider', 'event_type', 'created_at'], name='payments_pr_provide_cb0643_idx'),
        ),
        migrations.AddIndex(
            model_name='providerevent',
            index=models.Index(fields=['provider', 'created_at'], name='payments_pr_provide_f5e5ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_provider_event'),
        ),
    ]
