# Generated by Django 4.2.27 on 2026-02-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_providerevent_paymentintent_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='settlement_reference_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
