# Generated by Django 4.2.27 on 2026-02-28 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentintent_is_settled_paymentintent_settled_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentintent',
            new_name='idx_intent_provider_payment',
            old_name='payments_pa_provide_89c1ac_idx',
        ),
    ]
