# Generated by Django 4.2.27 on 2026-03-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_payments_pa_provide_89c1ac_idx_idx_intent_provider_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('line_hash', models.CharField(max_length=64)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=64)),
                ('submerchant_key', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'settlement_date'], name='idx_settlement_provider_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='settlementline',
            constraint=models.UniqueConstraint(fields=('provider', 'line_hash'), name='uq_settlement_line_provider_hash'),
        ),
    ]
