# Generated by Django 4.2.27 on 2026-03-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_settlementline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='gross_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='marketplace_conversation_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='platform_fee',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='submerchant_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='submerchant_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('marketplace_conversation_id', ''), _negated=True), fields=('marketplace_conversation_id',), name='uq_payment_intent_marketplace_conversation_nonempty'),
        ),
    ]
