# Generated by Django 4.2.30 on 2026-04-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_settlement_registry_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreversal',
            name='available_reversed_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='blocked_wallet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='manual_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='outstanding_exposure_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='pending_reversed_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreversal',
            name='review_status',
            field=models.CharField(choices=[('NONE', 'None'), ('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='NONE', max_length=16),
        ),
    ]
