# Generated by Django 4.2.30 on 2026-06-10 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0014_checkoutquotareservation_and_more'),
        ('businesses', '0019_official_four_marketplace_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurpriseDeal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('original_value_amount', models.PositiveBigIntegerField(help_text='Kurus cinsinden tahmini orijinal deger')),
                ('sale_price_amount', models.PositiveBigIntegerField(help_text='Kurus cinsinden satis fiyati')),
                ('currency', models.CharField(default='TRY', max_length=8)),
                ('quantity_total', models.PositiveIntegerField(default=0)),
                ('quantity_remaining', models.PositiveIntegerField(default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('pickup_window_start', models.DateTimeField()),
                ('pickup_window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('min_contents_note', models.CharField(blank=True, default='', max_length=255)),
                ('allergens_note', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surprise_deals', to='businesses.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surprise_deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurpriseDealReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('COMMITTED', 'Committed'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=16)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surprise_deal_reservations', to='orders.checkoutsession')),
                ('surprise_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='surprise_deals.surprisedeal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surprise_deal_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['surprise_deal', 'status'], name='idx_sdeal_res_deal_status'), models.Index(fields=['user', 'status'], name='idx_sdeal_res_user_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='surprisedealreservation',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='ck_sdeal_res_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='surprisedealreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_session__isnull', False)), fields=('checkout_session',), name='uq_sdeal_res_checkout_session'),
        ),
        migrations.AddIndex(
            model_name='surprisedeal',
            index=models.Index(fields=['business', 'status', 'pickup_window_start'], name='idx_sdeal_biz_status_start'),
        ),
        migrations.AddIndex(
            model_name='surprisedeal',
            index=models.Index(fields=['status', 'pickup_window_end'], name='idx_sdeal_status_end'),
        ),
        migrations.AddConstraint(
            model_name='surprisedeal',
            constraint=models.CheckConstraint(check=models.Q(('sale_price_amount__gt', 0)), name='ck_sdeal_sale_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='surprisedeal',
            constraint=models.CheckConstraint(check=models.Q(('original_value_amount__gte', models.F('sale_price_amount'))), name='ck_sdeal_original_gte_sale'),
        ),
        migrations.AddConstraint(
            model_name='surprisedeal',
            constraint=models.CheckConstraint(check=models.Q(('quantity_total__gte', 0)), name='ck_sdeal_qty_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='surprisedeal',
            constraint=models.CheckConstraint(check=models.Q(('quantity_remaining__gte', 0)), name='ck_sdeal_qty_remaining_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='surprisedeal',
            constraint=models.CheckConstraint(check=models.Q(('quantity_reserved__gte', 0)), name='ck_sdeal_qty_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='surprisedeal',
            constraint=models.CheckConstraint(check=models.Q(('quantity_remaining__lte', models.F('quantity_total'))), name='ck_sdeal_remaining_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='surprisedeal',
            constraint=models.CheckConstraint(check=models.Q(('pickup_window_end__gt', models.F('pickup_window_start'))), name='ck_sdeal_pickup_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='surprisedeal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'ACTIVE'), _negated=True), ('quantity_remaining__gt', 0), _connector='OR'), name='ck_sdeal_active_has_remaining'),
        ),
    ]
