# Generated by Django 4.2.30 on 2026-06-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surprise_deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surprisedeal',
            name='grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
