# Generated by Django 4.2.27 on 2026-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_businessprofile_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['district', 'is_active'], name='idx_bp_district_active'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['is_approved', 'is_active'], name='idx_bp_approved_active'),
        ),
    ]
