# Generated by Django 4.2.27 on 2026-02-21 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_idx_order_user_created_and_more'),
        ('businesses', '0003_businessprofile_idx_bp_district_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField(default=0, help_text='Kuruş cinsinden available')),
                ('pending_balance', models.PositiveBigIntegerField(default=0, help_text='Kuruş cinsinden pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='businesses.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('EARNING_PENDING', 'Earning -> Pending'), ('ELIGIBLE_MOVE', 'Pending -> Available'), ('PAYOUT', 'Payout')], max_length=32)),
                ('amount', models.BigIntegerField(help_text='Signed kuruş')),
                ('before_balance', models.PositiveBigIntegerField()),
                ('after_balance', models.PositiveBigIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
        ),
    ]
