# Generated by Django 4.2.27 on 2026-02-21 22:40

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_businesswallet_businesstransaction'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstransaction',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payouts.payout'),
        ),
        migrations.AddField(
            model_name='businesstransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='businesses.businesswallet'),
        ),
        migrations.AddIndex(
            model_name='businesstransaction',
            index=models.Index(fields=['wallet', '-id'], name='idx_businesstx_wallet_id'),
        ),
        migrations.AddIndex(
            model_name='businesstransaction',
            index=models.Index(fields=['order'], name='idx_businesstx_order'),
        ),
        migrations.AddIndex(
            model_name='businesstransaction',
            index=models.Index(fields=['payout'], name='idx_businesstx_payout'),
        ),
        migrations.AddConstraint(
            model_name='businesstransaction',
            constraint=models.CheckConstraint(check=models.Q(('after_balance', django.db.models.expressions.CombinedExpression(models.F('before_balance'), '+', models.F('amount')))), name='ck_businesstx_after_equals_before_plus_amount'),
        ),
        migrations.AddConstraint(
            model_name='businesstransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount', 0), _negated=True), name='ck_businesstx_amount_nonzero'),
        ),
    ]
