# Generated by Django 4.2.27 on 2026-03-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_businesstransaction_payout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='iyzico_submerchant_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='iyzico_submerchant_type',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'PERSONAL'), ('PRIVATE_COMPANY', 'PRIVATE_COMPANY'), ('LIMITED_OR_JOINT_STOCK', 'LIMITED_OR_JOINT_STOCK')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='payout_onboarding_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='payout_onboarding_status',
            field=models.CharField(choices=[('NONE', 'NONE'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='NONE', max_length=16),
        ),
    ]
