# Generated by Django 4.2.27 on 2026-03-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_businessprofile_iyzico_submerchant_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='iyzico_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='iyzico_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='iyzico_submerchant_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=16),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_contact_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_contact_surname',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_country',
            field=models.CharField(blank=True, default='Turkey', max_length=64),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_gsm_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_iban',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_identity_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_legal_company_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_tax_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='kyc_zip_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='iyzico_submerchant_type',
            field=models.CharField(blank=True, default='PERSONAL', max_length=16),
        ),
    ]
