# Generated by ChatGPT on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0007_businessprofile_iyzico_last_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="kyc_tax_office",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
