# Generated by Django 4.2.27 on 2026-04-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0015_alter_businessprofile_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('BEYLIKDUZU', 'Beylikdüzü')], default='BEYLIKDUZU', max_length=32)),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_other', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['district', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='display_priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='listing_type',
            field=models.CharField(choices=[('CONTRACTED', 'Contracted'), ('VOLUNTEER', 'Volunteer')], default='CONTRACTED', max_length=16),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='marketplace_is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['district', 'is_active', 'is_approved', 'is_listed', 'marketplace_is_visible'], name='idx_bp_marketplace_list'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['is_featured', 'display_priority'], name='idx_bp_featured_priority'),
        ),
        migrations.AddIndex(
            model_name='marketplacecategory',
            index=models.Index(fields=['district', 'is_active', 'sort_order'], name='idx_marketplace_category_list'),
        ),
        migrations.AddConstraint(
            model_name='marketplacecategory',
            constraint=models.UniqueConstraint(fields=('district', 'slug'), name='uq_marketplace_category_district_slug'),
        ),
        migrations.AddConstraint(
            model_name='marketplacecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_other', True)), fields=('district',), name='uq_marketplace_category_other_per_district'),
        ),
        migrations.AddField(
            model_name='businesscategoryassignment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_categories', to='businesses.businessprofile'),
        ),
        migrations.AddField(
            model_name='businesscategoryassignment',
            name='marketplace_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_assignments', to='businesses.marketplacecategory'),
        ),
        migrations.AddIndex(
            model_name='businesscategoryassignment',
            index=models.Index(fields=['business', 'is_active', 'sort_order'], name='idx_bca_business'),
        ),
        migrations.AddIndex(
            model_name='businesscategoryassignment',
            index=models.Index(fields=['marketplace_category', 'is_active'], name='idx_bca_category'),
        ),
        migrations.AddConstraint(
            model_name='businesscategoryassignment',
            constraint=models.UniqueConstraint(fields=('business', 'marketplace_category'), name='uq_business_marketplace_category_assignment'),
        ),
        migrations.AddConstraint(
            model_name='businesscategoryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('business',), name='uq_business_single_active_primary_marketplace_category'),
        ),
    ]
