# Generated by Django 4.2.27 on 2026-04-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0016_businesscategoryassignment_marketplacecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='badge_text',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='intro_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
