# Generated by Django 4.2.30 on 2026-05-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0017_businessprofile_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
