# Generated by Django 4.2.27 on 2026-02-21 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_idx_order_user_created_and_more'),
        ('businesses', '0004_businesswallet_businesstransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEarning',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField(help_text='Kuruş')),
                ('currency', models.CharField(default='TRY', max_length=8)),
                ('eligible_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ELIGIBLE', 'ELIGIBLE'), ('PAID', 'PAID')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='businesses.businessprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='business_earning', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField(help_text='Kuruş cinsinden')),
                ('currency', models.CharField(default='TRY', max_length=8)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('SENT', 'SENT'), ('CONFIRMED', 'CONFIRMED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='CREATED', max_length=16)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('provider_payout_id', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_error', models.TextField(blank=True, default='')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(default='manual', max_length=32)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='CREATED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField(help_text='Kuruş')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('earning', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_item', to='payouts.businessearning')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payouts.payout')),
            ],
        ),
        migrations.AddField(
            model_name='payout',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payouts.payoutbatch'),
        ),
        migrations.AddField(
            model_name='payout',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='businesses.businessprofile'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'next_retry_at'], name='idx_payout_status_retry'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['business', '-id'], name='idx_payout_business_id'),
        ),
        migrations.AddIndex(
            model_name='businessearning',
            index=models.Index(fields=['status', 'eligible_at'], name='idx_earning_status_eligible'),
        ),
        migrations.AddIndex(
            model_name='businessearning',
            index=models.Index(fields=['business', '-id'], name='idx_earning_business_id'),
        ),
    ]
