# Generated by Django 4.2.27 on 2026-02-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='last_error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='payout',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='locked_by',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('DISPATCHING', 'DISPATCHING'), ('SENT', 'SENT'), ('CONFIRMED', 'CONFIRMED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='CREATED', max_length=16),
        ),
    ]
