# Generated by Django 4.2.27 on 2026-02-23 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payouts', '0002_payout_last_error_at_payout_last_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='confirm_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payout',
            name='confirm_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='payout',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
