# Generated by Django 4.2.27 on 2026-03-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_payout_confirm_note_payout_confirm_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
