# Generated by Django 4.2.27 on 2026-03-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0004_payout_provider_reference'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider_reference',), name='uq_payout_provider_reference_nonempty'),
        ),
    ]
