# Generated by Django 4.2.27 on 2026-02-02 15:24

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallet_id_alter_wallettransaction_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallets_wal_wallet__a0330b_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['order'], name='wallets_wal_order_i_1c032b_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='wallets_wal_transac_7323ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('after_balance', django.db.models.expressions.CombinedExpression(models.F('before_balance'), '+', models.F('amount')))), name='ck_wallettx_after_equals_before_plus_amount'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount', 0), _negated=True), name='ck_wallettx_amount_nonzero'),
        ),
    ]
