# Generated by Django 4.2.27 on 2026-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallettransaction_wallets_wal_wallet__a0330b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='idx_wt_wallet_created'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-id'], name='idx_wt_wallet_id'),
        ),
    ]
