# Generated by Django 4.2.27 on 2026-02-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_wallettransaction_idx_wt_wallet_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pending_balance',
            field=models.PositiveIntegerField(default=0, help_text='Kuruş: settlement bekleyen bakiye'),
        ),
    ]
