# Generated by Django 4.2.27 on 2026-02-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_wallet_pending_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='pending_balance',
            field=models.PositiveBigIntegerField(default=0, help_text='Kuruş: settlement bekleyen bakiye'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('amount__gt', 0), ('transaction_type', 'TOP_UP')), models.Q(('transaction_type', 'TOP_UP'), _negated=True), _connector='OR'), name='ck_wt_topup_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('amount__gt', 0), ('transaction_type', 'REFUND')), models.Q(('transaction_type', 'REFUND'), _negated=True), _connector='OR'), name='ck_wt_refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('amount__lt', 0), ('transaction_type', 'PURCHASE')), models.Q(('transaction_type', 'PURCHASE'), _negated=True), _connector='OR'), name='ck_wt_purchase_amount_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type', 'PURCHASE'), ('order__isnull', False)), fields=('order',), name='uq_wt_purchase_per_order'),
        ),
    ]
