# Generated by Django 4.2.27 on 2026-02-16 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_providerevent_paymentintent_purpose_and_more'),
        ('wallets', '0006_alter_wallet_pending_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingWalletTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('TOPUP_PENDING', 'Topup Pending'), ('SETTLEMENT_OUT', 'Settlement Out')], max_length=32)),
                ('amount', models.BigIntegerField(help_text='Signed kuruş. TOPUP_PENDING:+, SETTLEMENT_OUT:-')),
                ('before_pending', models.PositiveBigIntegerField()),
                ('after_pending', models.PositiveBigIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='provider_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.providerevent'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['provider_event'], name='idx_wallettx_provider_event'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['payment_intent'], name='idx_wallettx_payment_intent'),
        ),
        migrations.AddField(
            model_name='pendingwallettransaction',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='pendingwallettransaction',
            name='provider_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.providerevent'),
        ),
        migrations.AddField(
            model_name='pendingwallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_transactions', to='wallets.wallet'),
        ),
        migrations.AddIndex(
            model_name='pendingwallettransaction',
            index=models.Index(fields=['wallet', '-id'], name='idx_pendingtx_wallet_id'),
        ),
        migrations.AddIndex(
            model_name='pendingwallettransaction',
            index=models.Index(fields=['provider_event'], name='idx_pendingtx_provider_event'),
        ),
        migrations.AddIndex(
            model_name='pendingwallettransaction',
            index=models.Index(fields=['payment_intent'], name='idx_pendingtx_payment_intent'),
        ),
        migrations.AddConstraint(
            model_name='pendingwallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('after_pending', django.db.models.expressions.CombinedExpression(models.F('before_pending'), '+', models.F('amount')))), name='ck_pendingtx_after_equals_before_plus_amount'),
        ),
        migrations.AddConstraint(
            model_name='pendingwallettransaction',
            constraint=models.CheckConstraint(check=models.Q(('amount', 0), _negated=True), name='ck_pendingtx_amount_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='pendingwallettransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('amount__gt', 0), ('transaction_type', 'TOPUP_PENDING')), models.Q(('transaction_type', 'TOPUP_PENDING'), _negated=True), _connector='OR'), name='ck_pendingtx_topup_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='pendingwallettransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('amount__lt', 0), ('transaction_type', 'SETTLEMENT_OUT')), models.Q(('transaction_type', 'SETTLEMENT_OUT'), _negated=True), _connector='OR'), name='ck_pendingtx_settlement_amount_negative'),
        ),
    ]
