# Generated by Django 4.2.30 on 2026-04-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_pendingwallet_constraint_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='restricted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='restriction_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
