# Generated by Django 4.2.27 on 2026-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_category_id_alter_menu_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['business', 'is_active'], name='idx_menu_business_active'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['category', 'is_active'], name='idx_menu_category_active'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['is_active'], name='idx_menu_active'),
        ),
    ]
