# Generated by Django 4.2.27 on 2026-04-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0017_businessprofile_badge_text_and_more'),
        ('menus', '0006_mediaasset_businessoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessoffer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businessoffer',
            name='label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='businessoffer',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='asset_role',
            field=models.CharField(choices=[('GALLERY', 'Gallery'), ('COVER', 'Cover'), ('LOGO', 'Logo'), ('THUMBNAIL', 'Thumbnail')], default='GALLERY', max_length=16),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='marketplace_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='businesses.marketplacecategory'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='menus.businessoffer'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['marketplace_category', 'is_active', 'sort_order'], name='idx_mediaasset_category_public'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['offer', 'is_active', 'sort_order'], name='idx_mediaasset_offer_public'),
        ),
    ]
