# Generated by Django 4.2.30 on 2026-06-04 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0008_menuitem_marketplace_category_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('quota_total', models.PositiveIntegerField(blank=True, null=True)),
                ('quota_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('quota_reserved', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='menus.menuitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_menu_item_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['menu_item', 'is_enabled'], name='idx_menu_quota_item_enabled')],
            },
        ),
        migrations.AddConstraint(
            model_name='menuitemquota',
            constraint=models.CheckConstraint(check=models.Q(('quota_total__gte', 0), ('quota_total__isnull', True), _connector='OR'), name='ck_menu_quota_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='menuitemquota',
            constraint=models.CheckConstraint(check=models.Q(('quota_remaining__gte', 0), ('quota_remaining__isnull', True), _connector='OR'), name='ck_menu_quota_remaining_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='menuitemquota',
            constraint=models.CheckConstraint(check=models.Q(('quota_reserved__gte', 0)), name='ck_menu_quota_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='menuitemquota',
            constraint=models.CheckConstraint(check=models.Q(('quota_total__isnull', True), ('quota_remaining__isnull', True), ('quota_remaining__lte', models.F('quota_total')), _connector='OR'), name='ck_menu_quota_remaining_lte_total'),
        ),
    ]
