# Generated by Django 4.2.30 on 2026-06-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_menuitemquota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='minimum_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
