# Generated by Django 4.2.30 on 2026-06-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_menuitem_minimum_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessoffer',
            name='offer_price_amount',
            field=models.PositiveIntegerField(help_text='KuruÅŸ cinsinden kampanya fiyatÄ±'),
        ),
    ]
