# Generated by Django 4.2.27 on 2026-02-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='method',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
