# Generated by Django 4.2.30 on 2026-07-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_systemlog_meta_systemlog_method_systemlog_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PAYMENT', 'Payment'), ('QR', 'QR Action'), ('LOGIN', 'Login'), ('OTHER', 'Other')], max_length=100),
        ),
    ]
