# Generated by Django 4.2.27 on 2026-01-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idempotency', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='idempotency_user_id_94bd2b_idx',
            old_name='idempotency_user_scope_key_idx',
        ),
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='idempotency_status_3062c7_idx',
            old_name='idempotency_status_created_at_idx',
        ),
    ]
