# Generated by Django 4.2.27 on 2026-02-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_expires_at_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qr_token',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
