# Generated by Django 4.2.27 on 2026-02-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_qr_token'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='idx_order_user_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', '-created_at'], name='idx_order_business_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='idx_order_status_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['qr_token'], name='idx_order_qr_token'),
        ),
    ]
