# Generated by Django 4.2.27 on 2026-04-01 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0006_mediaasset_businessoffer'),
        ('businesses', '0016_businesscategoryassignment_marketplacecategory_and_more'),
        ('orders', '0007_checkoutsession_and_order_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business_fee_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='business_net_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_fee_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='item_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='order_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_charged_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menus.menuitem'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CHECKED_OUT', 'Checked out'), ('ABANDONED', 'Abandoned'), ('CONVERTED', 'Converted')], default='ACTIVE', max_length=20)),
                ('subtotal_amount', models.PositiveIntegerField(default=0)),
                ('customer_fee_amount', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='TRY', max_length=8)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='businesses.businessprofile')),
                ('converted_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_carts', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_amount', models.PositiveIntegerField(default=0)),
                ('line_total_amount', models.PositiveIntegerField(default=0)),
                ('menu_item_name', models.CharField(max_length=160)),
                ('menu_item_snapshot', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menus.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'sort_order', 'id'], name='idx_orderitem_order_order')],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_amount', models.PositiveIntegerField(default=0)),
                ('line_total_amount', models.PositiveIntegerField(default=0)),
                ('menu_item_name', models.CharField(max_length=160)),
                ('menu_item_snapshot', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='orders.cart')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='menus.menuitem')),
            ],
            options={
                'indexes': [models.Index(fields=['cart', 'sort_order', 'id'], name='idx_cartitem_cart_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'menu_item'), name='uq_cartitem_cart_menu_item'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='idx_cart_user_status_updated'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['business', 'status', '-updated_at'], name='idx_cart_biz_status_upd'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user',), name='uq_cart_user_single_active'),
        ),
    ]
