# Generated by OpenCode on 2026-04-01

from django.db import migrations


def backfill_order_accounting_snapshot(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")

    for order in Order.objects.all().iterator(chunk_size=500):
        amount = int(order.amount or 0)
        update_fields = []

        if int(order.subtotal_amount or 0) == 0:
            order.subtotal_amount = amount
            update_fields.append("subtotal_amount")

        if int(order.total_charged_amount or 0) == 0:
            order.total_charged_amount = amount
            update_fields.append("total_charged_amount")

        if int(order.business_net_amount or 0) == 0:
            order.business_net_amount = max(int(order.subtotal_amount or 0) - int(order.business_fee_amount or 0), 0)
            update_fields.append("business_net_amount")

        if int(order.item_count or 0) == 0:
            order.item_count = 1
            update_fields.append("item_count")

        if not order.pricing_snapshot:
            order.pricing_snapshot = {
                "currency": "TRY",
                "subtotal_amount": int(order.subtotal_amount or 0),
                "customer_fee_amount": int(order.customer_fee_amount or 0),
                "business_fee_amount": int(order.business_fee_amount or 0),
                "total_charged_amount": int(order.total_charged_amount or 0),
                "business_net_amount": int(order.business_net_amount or 0),
            }
            update_fields.append("pricing_snapshot")

        if not order.order_snapshot:
            order.order_snapshot = {
                "legacy_order_backfilled": True,
            }
            update_fields.append("order_snapshot")

        if update_fields:
            order.save(update_fields=update_fields)

        has_items = OrderItem.objects.filter(order_id=order.id).exists()
        if not has_items and order.menu_id and amount > 0:
            OrderItem.objects.create(
                order_id=order.id,
                menu_item_id=order.menu_id,
                quantity=1,
                unit_price_amount=amount,
                line_total_amount=amount,
                menu_item_name="",
                menu_item_snapshot={
                    "menu_item_id": order.menu_id,
                    "backfilled_from_legacy_order": True,
                },
                sort_order=0,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_business_fee_amount_order_business_net_amount_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_order_accounting_snapshot, migrations.RunPython.noop),
    ]
