# Generated by Django 4.2.27 on 2026-04-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_mediaasset_businessoffer'),
        ('orders', '0009_backfill_order_accounting_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='business_fee_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='business_net_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='orders.cart'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='cart_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='currency',
            field=models.CharField(default='TRY', max_length=8),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='customer_fee_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='item_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='platform_total_fee_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='subtotal_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='menus.menuitem'),
        ),
    ]
