# Generated by Django 4.2.30 on 2026-04-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_businessoffer_description_businessoffer_label_and_more'),
        ('orders', '0011_remove_checkoutsession_legacy_item_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(blank=True, editable=False, help_text='Internal representative item pointer. Do not use in product APIs.', null=True, on_delete=django.db.models.deletion.PROTECT, to='menus.menuitem'),
        ),
    ]
