# Generated by Django 4.2.30 on 2026-06-04 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_menuitemquota_and_more'),
        ('orders', '0013_checkoutsession_cashier_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutQuotaReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('COMMITTED', 'Committed')], default='RESERVED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_reservations', to='orders.checkoutsession')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_quota_reservations', to='menus.menuitem')),
            ],
            options={
                'indexes': [models.Index(fields=['checkout_session', 'status'], name='idx_quota_res_session_status'), models.Index(fields=['menu_item', 'status'], name='idx_quota_res_menu_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='checkoutquotareservation',
            constraint=models.UniqueConstraint(fields=('checkout_session', 'menu_item'), name='uq_quota_res_session_menu_item'),
        ),
        migrations.AddConstraint(
            model_name='checkoutquotareservation',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='ck_quota_res_quantity_positive'),
        ),
    ]
