# Generated by Django 4.2.30 on 2026-06-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_checkoutquotareservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='source_type',
            field=models.CharField(choices=[('CART', 'Cart'), ('SURPRISE_DEAL', 'Surprise deal')], default='CART', max_length=24),
        ),
    ]
