# Generated by Django 4.2.30 on 2026-06-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_PAID', 'Order Paid'), ('ORDER_CONSUMED', 'Order Consumed'), ('ORDER_USED', 'Order Used'), ('PAYMENT_SETTLED', 'Payment Settled'), ('PAYOUT_SENT', 'Payout Sent'), ('PAYOUT_CONFIRMED', 'Payout Confirmed'), ('BALANCE_LOW', 'Balance Low'), ('SYSTEM_BROADCAST', 'System Broadcast'), ('USER_REMINDER', 'User Reminder'), ('EMAIL_BROADCAST', 'Email Broadcast')], max_length=32),
        ),
    ]
